version: 0.0
os: linux

files:             
  - source: ./webapp/noteapp/target/noteapp-1.war
    destination: /opt/tomcat/apache-tomcat-9.0.16/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
