spring:
  profile: dev
  datasource:
    url: jdbc:mysql://csye6225.cnewmoox6eb2.us-east-1.rds.amazonaws.com:3306/csye6225
    password: root-ubuntu
    username: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 12MB

server:
  port: 9091

amazonProperties:
  endpoint: https://s3.us-east-1.amazonaws.com
  bucketName: csye6225-spring2019-dongak.me.csye6225.com